# MongoDB URI
#spring:
#  data:
#    mongodb:
#      uri:mongodb://localhost:27017/journaldb
spring:
  data:
    redis:
        host: redis-12196.c15.us-east-1-2.ec2.redns.redis-cloud.com
        port: 12196
        password: 4laiRpDlo9HTxBhbFS23V2dMGeUbzRBh
    #      uri: redis://default:4laiRpDlo9HTxBhbFS23V2dMGeUbzRBh@redis-12196.c15.us-east-1-2.ec2.redns.redis-cloud.com:12196
    mongodb:
      uri: mongodb+srv://angadgupta506:2KPoPcMTNStEeVAT@cluster0.1pt3iaa.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: journaldb
      auto-index-creation: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: angadgupta506@gmail.com
    password: wbbydmxndwhxhwpw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  kafka:
    bootstrap-servers: pkc-921jm.us-east-2.aws.confluent.cloud:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: weekly-sentiment-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: com.example.journalApp.model
    properties:
      security:
        protocol: SASL_SSL
      sasl:
        mechanism: PLAIN
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username='MMFB235EBCJHY2B2' password='9HKL4bWuSbYc3STAFVeaOtmbuDCtCVX1r7DDj1gs63gF7OP7aOUlE7mrY35PmHK+';
      session:
        timeout:
          ms: 45000

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

server:
  port: 8080

weather:
  api:
    key: 3929f268c953a6b5ae28491010166164




